
import { AiChatLogModel } from '../models/AiChatLog';
import { AiChatEvaluationModel } from '../models/AiChatEvaluation';
import { config } from '../config/env';
import OpenAI from 'openai';
import { HttpsProxyAgent } from 'https-proxy-agent';
import { AiPromptModel } from '../models/AiPrompt';
import { AiSchemaDocModel } from '../models/AiSchemaDoc';

export class EvaluationService {

    /**
     * Evaluate a specific chat log
     */
    static async evaluateLog(logId: number): Promise<void> {
        try {
            console.log(`Starting evaluation for log ${logId}...`);
            const log = await AiChatLogModel.findById(logId);
            if (!log) {
                console.error(`Log ${logId} not found`);
                return;
            }

            // Skip if already evaluated? Or allow re-evaluation? 
            // For now, allow re-eval.

            // 0. Prepare Data for Judge
            // Fetch current Schema and Prompts to give context to the Judge
            const schemas = await AiSchemaDocModel.findAll();
            const schemaContext = schemas.map(s => `${s.table_name}: ${s.description}`).join('\n');
            const promptContext = log.prompt_used || "N/A";

            // 1. Construct Judge Prompt
            const systemPrompt = `
            You are a QA Lead for a Text-to-SQL RAG system.
            Your job is to evaluate the quality of the AI's response to a user query.
            
            Input Data:
            - User Query: The user's natural language question.
            - Generated SQL: The SQL generated by the AI (if any).
            - Key Schema Context: Brief description of available tables.
            - AI Answer: The final text response provided to the user.
            - User Feedback: ${log.feedback_score !== 0 ? (log.feedback_score === 1 ? "Positive (Thumbs Up)" : "Negative (Thumbs Down)") : "None"} ${log.feedback_text ? `Reason: ${log.feedback_text}` : ""}
            
            Evaluation Criteria:
            1. **SQL Correctness**: Is the SQL syntactically and logically correct based on common sense and the provided context?
            2. **Data Hallucination**: Did the AI invent columns or tables?
            3. **Intent Match**: Did the SQL actually answer the user's intent?
            4. **Response Quality**: Is the final text answer helpful and accurate based on the SQL result?
            
            Output JSON Format:
            {
                "score": <0-100 integer>,
                "issues": ["<Tag1>", "<Tag2>"], // e.g., "SQL_SYNTAX_ERROR", "SCHEMA_HALLUCINATION", "INTENT_MISMATCH", "FORMATTING_ISSUE", "NO_DATA_IS_OK"
                "suggestion": "<Short advice to fix the Prompt or Schema>"
            }
            `;

            const userContent = `
            User Query: ${log.user_query}
            Generated SQL: ${log.sql_generated}
            Context/Prompt Used: ${promptContext.substring(0, 1000)}...
            AI Answer: ${log.final_answer}
            Schema Summary: ${schemaContext}
            `;

            // 2. Call LLM (DeepSeek or Gemini)
            // Use DeepSeek for "Reasoning" capability if available, else Gemini
            const evaluation = await this.callLLMJudge(systemPrompt, userContent);

            // 3. Save Evaluation
            await AiChatEvaluationModel.create({
                log_id: logId,
                score: evaluation.score,
                issues: evaluation.issues,
                suggestion: evaluation.suggestion
            });

            console.log(`Evaluation saved for log ${logId}. Score: ${evaluation.score}`);

        } catch (error) {
            console.error(`Failed to evaluate log ${logId}:`, error);
        }
    }

    private static async callLLMJudge(system: string, user: string): Promise<{ score: number, issues: string[], suggestion: string }> {
        // Implementation using DeepSeek (or Gemini as fallback)
        if (!config.ai.deepseekKey) throw new Error("No AI Key enabled for Evaluation");

        const options: any = {
            baseURL: config.ai.deepseekUrl,
            apiKey: config.ai.deepseekKey
        };
        if (config.proxy) options.httpAgent = new HttpsProxyAgent(config.proxy);
        const openai = new OpenAI(options);

        try {
            const completion = await openai.chat.completions.create({
                messages: [
                    { role: "system", content: system },
                    { role: "user", content: user }
                ],
                model: "deepseek-chat",
                temperature: 0.1,
                response_format: { type: 'json_object' }
            });

            const content = completion.choices[0].message.content || "{}";
            const parsed = JSON.parse(content);
            return {
                score: parsed.score || 0,
                issues: parsed.issues || [],
                suggestion: parsed.suggestion || ""
            };
        } catch (e) {
            console.error("LLM Judge failed", e);
            return { score: 0, issues: ["EVALUATION_FAILED"], suggestion: "System failed to evaluate" };
        }
    }

    /**
     * Triggered by cron or manual request to sniff out bad chats
     */
    static async runBatchEvaluation(limit = 10): Promise<void> {
        // Find unevaluated logs? Or just recent ones?
        // For simplicity, find recent logs that have negative feedback OR are just recent
        // TODO: Implement query for "Unevaluated Logs"
    }
}
